# Generated by Django 4.2.5 on 2023-11-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('san', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='myblog/%Y/%m/%d')),
                ('likes', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Dawlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('san', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='myblog/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('slug', models.SlugField(max_length=125, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category')),
            ],
            options={
                'verbose_name_plural': 'Dawlet',
            },
        ),
    ]
